services:
  streamlit_app:
    build: ./app
    working_dir: /streamlit_app
    container_name: streamlit_demo
    ports:
      - "8501:8501"
    restart: always
    depends_on:
      - openwebui
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - openwebui_data:/app/backend/data
    depends_on:
      - ollama
      - qdrant
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    environment:
      RAG_EMBEDDING_MODEL: "sentence-transformers/all-mpnet-base-v2"
      RAG_QDRANT_URL: "http://qdrant:6333"
      OFFLINE_MODE: true
      OLLAMA_API_URL: "http://ollama:11434"
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - C:/Users/witze/.ollama:/root/.ollama   
    entrypoint: >
      sh -c "ollama serve"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage:z
    restart: always

volumes:
  openwebui_data:
    external: true
    name: openwebuidemo_open-webui
  qdrant_data:
    external: true
    name: openwebuidemo_qdrant_storage